cache: apt
language: python
sudo: false
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
python:
  - 3.6
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - chmod 755 create_env.sh
install:
  - travis_retry . ./create_env.sh
  - python --version
  - pip --version
  # coveralls requires coverage==4.0.3, recent versions of pytest-cov require coverage>=4.4
  - travis_retry pip install coverage==4.0.3 nose pytest-pep8 pytest-cov==2.5.1 python-coveralls
script:
  - which python
  - nosetests -v --with-coverage --cover-tests --cover-package=synthit --ignore-files=synthit/models/br.py tests
after_success:
  - coveralls
